"""first migration

Revision ID: acccd50c0cd9
Revises: 
Create Date: 2023-05-24 21:09:44.671848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acccd50c0cd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('keywords', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=128), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=2), nullable=False),
    sa.Column('is_entry', sa.BOOLEAN(), nullable=False),
    sa.Column('datetime', sa.DATETIME(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
